# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_book_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='read',
        ),
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.CharField(default='', max_length=500),
        ),
    ]
