# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-25 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_book_shelf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='shelf',
        ),
    ]
